name: RegionsVisible
version: '1.0'
main: org.meekle.mc.show_messages.Show_messages
depend: [ WorldGuard, ActionBarAPI ]
authors: [ Meekle ]
description: See your, custom and another region!
commands:
  sm-reload:
    description: Reload
    usage: /rv-reload
    aliases: [rv-rl]
  sm-add:
    description: Add region
    usage: /rv-add <region_name> <name_in_actionBar>
  sm-remove:
    description: Remove region
    usage: /rv-remove <region_name>




